name: your-workflow-name # workflow name
on: [push, workflow_dispatch] # on: [trigger]
jobs:
  run:
    runs-on: ubuntu-latest # machine to run on
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    permissions:
      issues: write
      pull-requests: write
    container: ghcr.io/iterative/cml:0-dvc2-base1 # optional
    steps:
      - uses: actions/checkout@v4 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create CML report
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md

          echo "## Data viz" >> report.md
          echo '![](./feature_importance.png "Feature Importance")' >> report.md
          cml comment create report.md
          echo '![](./residuals.png "Residuals")' >> report.md
          cml comment create report.md
